### ISSUE TITLE
NameError: name 'lut_aamask' is not defined

### ISSUE THREAD

**Issue by WolframRhodium** [pwinner/Vapoursynth_Interestring_Masks#1]
https://github.com/pwinner/Vapoursynth_Interestring_Masks/blob/eae49a7cde59beff67c9cace7625d250d707e34f/AA_Masks/aamask_Usingnnedi3/MysteryMask.py#L17

**Comment by MysteryDove** [comment]
> https://github.com/pwinner/Vapoursynth_Interestring_Masks/blob/eae49a7cde59beff67c9cace7625d250d707e34f/AA_Masks/aamask_Usingnnedi3/MysteryMask.py#L17

Thanks! I haven't tested this before. Now it should works!
